# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(488, 284)
        self.gridLayoutWidget = QtWidgets.QWidget(Settings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 461, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_Logger = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Logger.setObjectName("comboBox_Logger")
        self.comboBox_Logger.addItem("")
        self.comboBox_Logger.addItem("")
        self.comboBox_Logger.addItem("")
        self.comboBox_Logger.addItem("")
        self.gridLayout.addWidget(self.comboBox_Logger, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_BaudRate = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_BaudRate.setObjectName("comboBox_BaudRate")
        self.comboBox_BaudRate.addItem("")
        self.comboBox_BaudRate.addItem("")
        self.comboBox_BaudRate.addItem("")
        self.comboBox_BaudRate.addItem("")
        self.gridLayout.addWidget(self.comboBox_BaudRate, 2, 1, 1, 1)
        self.checkBox_CAN1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_CAN1.setObjectName("checkBox_CAN1")
        self.gridLayout.addWidget(self.checkBox_CAN1, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox_CAN2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_CAN2.setObjectName("checkBox_CAN2")
        self.gridLayout.addWidget(self.checkBox_CAN2, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.comboBox_ComPort = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_ComPort.setMaximumSize(QtCore.QSize(107, 30))
        self.comboBox_ComPort.setObjectName("comboBox_ComPort")
        self.gridLayout.addWidget(self.comboBox_ComPort, 0, 2, 1, 1)
        self.pushButton_Refresh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.gridLayout.addWidget(self.pushButton_Refresh, 0, 3, 1, 1)
        self.Btn_Ok = QtWidgets.QPushButton(Settings)
        self.Btn_Ok.setGeometry(QtCore.QRect(20, 230, 56, 31))
        self.Btn_Ok.setObjectName("Btn_Ok")
        self.Btn_Cancel = QtWidgets.QPushButton(Settings)
        self.Btn_Cancel.setGeometry(QtCore.QRect(90, 230, 56, 31))
        self.Btn_Cancel.setObjectName("Btn_Cancel")

        self.retranslateUi(Settings)
        self.Btn_Cancel.clicked.connect(Settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Dialog"))
        self.comboBox_Logger.setItemText(0, _translate("Settings", "KORLAN"))
        self.comboBox_Logger.setItemText(1, _translate("Settings", "WAVESHARE_A"))
        self.comboBox_Logger.setItemText(2, _translate("Settings", "PCAN"))
        self.comboBox_Logger.setItemText(3, _translate("Settings", "PCAN_PRO"))
        self.label_3.setText(_translate("Settings", "Baud Rate"))
        self.label_2.setText(_translate("Settings", "Channels"))
        self.comboBox_BaudRate.setCurrentText(_translate("Settings", "125"))
        self.comboBox_BaudRate.setItemText(0, _translate("Settings", "125"))
        self.comboBox_BaudRate.setItemText(1, _translate("Settings", "250"))
        self.comboBox_BaudRate.setItemText(2, _translate("Settings", "500"))
        self.comboBox_BaudRate.setItemText(3, _translate("Settings", "1000"))
        self.checkBox_CAN1.setText(_translate("Settings", "CAN1"))
        self.label.setText(_translate("Settings", "Device"))
        self.checkBox_CAN2.setText(_translate("Settings", "CAN2"))
        self.label_4.setText(_translate("Settings", "kbps"))
        self.pushButton_Refresh.setText(_translate("Settings", "Refresh"))
        self.Btn_Ok.setText(_translate("Settings", "Apply"))
        self.Btn_Cancel.setText(_translate("Settings", "Cancel"))
